#pragma once
#include <filesystem>
#include <map>
#include <string>
#include <optional>

#include "ImageFileName.h"

/**
 * @class Reads list of files in directory that match pattern generated by pdfimages -p
 */
class FileList
{
public:
   /**
    * Reads files for directory and creates lookup
    *
    * @param dir Directory of extracted images - usually current "."
    * @param prefix Prefix used in extraction of images with pdfimages
    */
   FileList(const std::string& dir, const std::string& prefix);

   auto lookup(int number) -> std::optional<ImageFileName>;

private:
   [[nodiscard]] static auto getFileNumber(const std::string &filename) -> int;

   std::map<int, ImageFileName> paths_;
};
